### ISSUE TITLE
Add a pizeo buzzer

### ISSUE THREAD

**Issue by dhl** [dimsumlabs/dootdoorlock#3]
It is so easy to lose your thoughts to exciting ideas and wonderful experiments at the Dim Sum Labs.

Last night, another DSL member and I were having a discussion when, suddenly, we realized that it was 12:37am. We did a mad dash for the Kowloon-bound train, and we got on the train **just before** the door closed a few inches behind us. One of us almost had a heart attack (I am not going to say who).

So, after catching our breaths, we thought, "wouldn't it be nice to have a buzzer or siren to alert members to leave now if they want to catch the last train?"

What do you think if we connect a piezo buzzer to the doorlock Pi to alert space users, among other uses, that they should get ready to leave if they want to catch the last train?

Just a thought!

**Comment by tomgrek** [comment]
I think a regular speaker would be easier and better, just plug it in and eg can then put a voice synthesizer on the pi to read out the time each hour, or tweets etc. Go for it if you wanna.Just one thing to note, the github is not up to date, I hacked some code directly on the pi, so push it or take a backup first...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  From: David LeungSent: Thursday, March 6, 2014 13:09To: dimsumlabs/dootdoorlockReply To: dimsumlabs/dootdoorlockSubject: [dootdoorlock] Add a pizeo buzzer (#3)It is so easy to lose your thoughts to exciting ideas and wonderful experiments at the Dim Sum Labs.

Last night, another DSL member and I were having a discussion when, suddenly, we realized that it was 12:37am. We did a mad dash for the Kowloon-bound train, and we got on the train just before the door closed a few inches behind us. One of us almost had a heart attack (I am not going to say who).

So, after catching our breaths, we thought, "wouldn't it be nice to have a buzzer or siren to alert members to leave now if they want to catch the last train?"

What do you think if we connect a piezo buzzer to the doorlock Pi to alert space users, among other uses, that they should get ready to leave if they want to catch the last train?

Just a thought!

—Reply to this email directly or view it on GitHub.

**Comment by dhl** [comment]
Thanks Tom!

**Comment by dhl** [comment]
Closing this issue for now...
